### ISSUE TITLE
Errors on load - V10

### ISSUE THREAD

**Issue by JeffreyRijkse** [johnnolan/encounter-stats#222]
I get both of these errors on load - I don't think they impede functionality but its red and is yelling at me :D

![image](https://user-images.githubusercontent.com/78631300/190233054-87ae9ea5-0ead-4f4e-90b2-424d1af3dc57.png)

**Comment by johnnolan** [comment]
Ahh, I hate it when my code shouts at people, sorry! :D

Thanks for the bug report, by any chance is there an active combat in progress and this is the first time you have used it?

This error is saying there is a combat active but the module does not have any knowledge of it starting.

Anyway, let me know if it stops working for you and I will ask for some more information, otherwise I am going to clean up that bit of code to prevent it erroring and handle it better.

**Comment by johnnolan** [comment]
Amazing breakdown, that helps a lot, will add those as test scenarios and change the way it handles them. Will also look at handling multiple combats, not something I do so didn't really think about it.

Will close this issue and add two new feature tickets referencing this one if you want to monitor progress.
